import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import np_utils
from keras.utils.visualize_util import plot
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
